-- CREATE TABLE LOT (
--   ID INTEGER IDENTITY PRIMARY KEY,
--  FEE_ID INTEGER
-- );
--
-- INSERT INTO LOT (ID,FEE_STRUCTURE_ID) VALUES (1,1);
--
--



CREATE TABLE FEE_STRUCTURE(

LOT_ID INTEGER,
TIME_INFO VARCHAR(256),
START_TIME INT,
END_TIME INT,
PRICE INT,
FEE_ID INT

);

INSERT INTO FEE_STRUCTURE (LOT_ID, TIME_INFO, START_TIME, END_TIME, PRICE, FEE_ID ) VALUES (1,'to 1 hour',0,60,10,1);
INSERT INTO FEE_STRUCTURE (LOT_ID, TIME_INFO, START_TIME, END_TIME, PRICE, FEE_ID ) VALUES (1,'to 2 hours',61,120,20,2);
INSERT INTO FEE_STRUCTURE (LOT_ID, TIME_INFO, START_TIME, END_TIME, PRICE, FEE_ID ) VALUES (1,'to 3 hours',121,180,50,3);
INSERT INTO FEE_STRUCTURE (LOT_ID, TIME_INFO, START_TIME, END_TIME, PRICE, FEE_ID ) VALUES (1,'to 5 hours',181,240,60,4);
INSERT INTO FEE_STRUCTURE (LOT_ID, TIME_INFO, START_TIME, END_TIME, PRICE, FEE_ID ) VALUES (1,'to 7 hours',241,300,75,5);
